### ISSUE TITLE
chatbot.create_direct_channel() no longer works, it worked before (no changes made to the working program) but now it gives this error

### ISSUE THREAD

**Issue by swedenismycity** [j-hc/Reddit_ChatBot_Python#14]
20:24, INFO: LOGI{"key":"48fbfda2b8762e71fb4f7d84b3edc8479aa16021","disable_supergroup_mack":false,"require_auth_for_profile_image":false,"ping_interval":15,"ekey":"D5yjur2w9rfeHVKT8BwGkMJDc_QroYuFLqaJap4iVhkec4OOiIw0NwxVPcOpKgKbjEh70hZLY88JCWn6hEfV9A","preferred_languages":[],"pong_timeout":5,"bc_duration":0,"login_ts":1660760680991,"unread_cnt":{"all":0,"ts":1660760680996},"is_hide_me_from_friends":false,"max_unread_cnt_on_super_group":100,"discovery_keys":[],"reconnect":{"mul":2,"max_interval":20,"interval":2,"retry_cnt":-1},"use_reaction":true,"user_id":"t2_1yxto4q6","nickname":"SwedenIsMyCity0403","profile_url":"","metadata":{}}

Exception ignored in thread started by: <bound method WebSockClient._response_loop of <Reddit_ChatBot_Python._ws_client.WebSockClient object at 0x7f3649a4ff10>>
Traceback (most recent call last):
  File "/home/anon/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/_ws_client.py", line 70, in _response_loop
    if func(resp):
  File "/home/anon/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/_events.py", line 16, in hook
    return func(resp)
  File "/home/anon/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/_events.py", line 76, in hook
    return func(resp)
  File "/home/anon/project/reddit/ripoff.py", line 23, in get_blacklist
    dm_channel = chatbot.create_direct_channel("KolobConquerer")
  File "/home/anon/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/chatbot.py", line 200, in create_direct_channel
    channel = self.create_channel(nicknames=[self.__WebSocketClient.own_name, nickname], group_name="")
  File "/home/anon/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/chatbot.py", line 195, in create_channel
    channel = super().create_channel(nicknames, group_name)
  File "/home/anon/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/_api/tools.py", line 192, in create_channel
    response = self.__handled_req(method='POST', uri=f'{S_REDDIT}/api/v1/sendbird/group_channels',
  File "/home/anon/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/_api/tools.py", line 47, in __handled_req
    raise APIException(response.text)
Reddit_ChatBot_Python._utils.exceptions.APIException:

**Comment by j-hc** [comment]
it works fine for me. and you didnt get any error back from the reddit so im guessing this was a one time thing probably?

**Comment by swedenismycity** [comment]
You're right, it just took a while and it resolved itself. You can close
the issue, sorry to bother you.

Den tors 18 aug. 2022 kl 15:55 skrev j-hc ***@***.***>:
