### ISSUE TITLE
Can't authenticate with password

### ISSUE THREAD

**Issue by Roosteridk** [j-hc/Reddit_ChatBot_Python#21]
Traceback (most recent call last):
  File "/workspaces/codespaces-blank/bot.py", line 5, in <module>
    chatbot = ChatBot(reddit_auth)
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/Reddit_ChatBot_Python/chatbot.py", line 22, in __init__
    sb_access_token, user_id = self._load_session(authentication._get_repr_pkl())
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/Reddit_ChatBot_Python/chatbot.py", line 231, in _load_session
    return self._load_session(pkl_name, force_reauth=True)
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/Reddit_ChatBot_Python/chatbot.py", line 225, in _load_session
    self.__r_authentication.authenticate()
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/Reddit_ChatBot_Python/reddit_auth.py", line 67, in authenticate
    raise WrongCreds("Wrong username or password")
Reddit_ChatBot_Python._utils.exceptions.WrongCreds: Wrong username or password

**Comment by Roosteridk** [comment]
Using the latest version (1.4.9) btw

**Comment by Migelangelo1** [comment]
I'm having the same issue. Version 1.4.9 too. It started appearing recently. Username and password are 100% correct.

**Comment by NathanTech7713** [comment]
Hi,

Same here. Exact same issue.

**Comment by NathanTech7713** [comment]
Hi there,

I'm actually still experiencing this after updating today from the repo, do I have to do something (delete a temp file etc) to make this work?

Sorry!

**Comment by maxkross** [comment]
I am also having the same issue
