### ISSUE TITLE
Getting EOFError: Ran out of input error when trying to run chat cli example.

### ISSUE THREAD

**Issue by mysteries-of-inrinth** [j-hc/Reddit_ChatBot_Python#8]
Full Error:
```
Traceback (most recent call last):
  File "/home/-----/local/lib/python3.10/site-packages/Reddit_ChatBot_Python/chatbot.py", line 230, in _load_session
    self.__r_authentication = pickle.load(session_store_f)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/-----/Desktop/multi-poster/chat.py", line 7, in <module>
    chatbot = ChatBot(print_chat=True, store_session=True, log_websocket_frames=False, authentication=reddit_authentication)
  File "/home/-----/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/chatbot.py", line 23, in __init__
    sb_access_token, user_id = self._load_session(authentication._get_repr_pkl())
  File "/home/-----/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/chatbot.py", line 232, in _load_session
    return self._load_session(pkl_name, force_reauth=True)
  File "/home/-----/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/chatbot.py", line 226, in _load_session
    self.__r_authentication.authenticate()
  File "/home/-----/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/reddit_auth.py", line 71, in authenticate
    self.api_token = self._get_api_token()
  File "/home/-----/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/reddit_auth.py", line 84, in _get_api_token
    return response.json()['access_token']
KeyError: 'access_token'
```

**Comment by j-hc** [comment]
im guessing this is just a hiccup from reddit's side. it happens often. i pushed a commit with handling of the case when access_token is not available. you can try with that and see the api response from reddit.
